title: Yuvraj # name of the site
author: Yuvraj Singh # name of site's author
email: singhyuvrajf1@gmail.com # email of site's author
url: https://yuvrajxms09.github.io # root address of the site
baseurl: "/" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed) 
  <p> <span style="color: #FFFFFF; font-size: 1.2em;">ML Engineer</span> <br> <span style="color: #1DB954;">Always interested in collaborations : feel free to reach out!</span> <br>  <br> <span style="color: #1DB954;">interests : tennis, F1, dancing</span> <br> <span style="color: #1DB954;">currently : finetuning LLMs and exploring bio/ML applications</span> <br> </p>

# permalink: /:year/:month/:day/:title.html

favicon: "icons8-disco-ball-96.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  reco:
    output: true
